[package]
name = "page"
version = "0.1.0"
edition = "2021"


[dependencies]

reqwest = { version = "0.12.1", features = ["json"] }
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.36.0", features = ["full"] }
serde_json = "1.0.114"
log = "0.4.21"
env_logger = "0.11.3"
